options:
  auto-update: true
  instability-update-interval: 10
  enable-instability-effects: true
  daxi-regen-update-interval: 10
  enable-daxi-regen-effects: true
  give-guide-on-first-join: true
  polarizer-affinity-chance: 40
  zot-required-charge: 1000
  unstable-death-message: " tried to become unstable. They succeeded."
  daxi-message-intro: "You feel power flowing through your veins."
  daxi-message-strength: "Your strikes are now more effective."
  daxi-message-absorption: "You feel healthier."
  daxi-message-fortitude: "Enemy strikes are now less effective."
  daxi-message-saturation: "You won't need food for a while."
  daxi-message-regeneration: "You've acquired permanent self-healing."
  daxi-message-radiation-immunity: "Radiation cannot budge you no more."
  daxi-message-fast-walker: "Now you can race usain bolt."
  daxi-message-transcendent-heal: "Now you are perfect..."
  daxi-message-nuker: "Fast minors."
  daxi-message-undyne: "Via determination, you can now rise from the dead."
  already-have-daxi-effect: "You already have this Daxi effect!"
  droppable-unstable-ingots: true
  unstable-ingots-message-undroppable: "Unstable Ingots are undroppable!"

daxi-effects:
  strength-level: 3
  absorption-level: 5
  fortitude-level: 4
  saturation-level: 1
  regeneration-level: 2
  speed-level: 7
  transcendent-heal-level: 10
  nuker-level: 7


guide:
  recieve-on-first-join: true

debug:
  radiation: true
  daxi-effects: true